### PR TITLE
Allow passing in custom history to BrowserRouter

### LINKED ISSUE #9: Custom history doesn't support basename
[Issuehunt badges](https://issuehunt.io/r/sindresorhus/react-router-util/issues/9)

Since the exported `BrowserRouter` creates its own history, without allowing for configuration from props, this library doesn't support using a `basename`. I will toy around with what this could look like and if I find a nice solution I'll open a PR

> There is a $40.00 open bounty on this issue. Add more on [Issuehunt](https://issuehunt.io/r/sindresorhus/react-router-util/issues/9).
> - Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/react-router-util/) to discover more funded issues.
> - Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on Issuehunt to raise funds.

### PR DESCRIPTION
**Pull request by alexzherdev**
Fixes #9

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you include a test?

**Comment by alexzherdev** [comment]
Added. Not sure if there is a less roundabout way to test this...

**Comment by sindresorhus** [comment]
You need to update the docs too.

**Comment by sindresorhus** [comment]
Thanks :)

**Pull request merged**
